services:
  backend:
    build:
      context: backend/.
    image: nestjs-backend:latest
    env_file:
      - backend/.env
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  frontend:
    build:
      context: frontend/.
    image: react-frontend:latest
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    depends_on:
      - backend
  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/var/lib/mongodb/data
volumes:
  mongodb-data:
networks:
  default:
    driver: bridge
    name: my-network