services:
  backend:
    build:
      context: backend/.
    container_name: nestjs-backend
    env_file:
      - backend/.env
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  frontend:
    build:
      context: frontend/.
    container_name: react-frontend
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    depends_on:
      - backend
  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/var/lib/mongodb/data
volumes:
  mongodb-data: